import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { Analytics } from "@vercel/analytics/react";

const dmsans = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ScribeRevise | AI-Powered Message Revisions",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={dmsans.className}>
        <Header />
        {children}
        <Analytics />
      </body>
    </html>
  );
}
