import type { Metadata } from "next";
import { Arimo, DM_Sans, IBM_Plex_Sans, Inter, Libre_Franklin, Manrope, Noto_Sans, Nunito, Nunito_Sans, Plus_Jakarta_Sans, Prompt, Raleway, Roboto, Source_Sans_3, Work_Sans } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const dmsans = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={dmsans.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
